channels:
  - conda-forge
dependencies:
  - intake
  - intake-xarray
  - fsspec
  - s3fs
  - conda-forge/label/h5py_dev::h5py
  - h5netcdf
  - matplotlib
  - holoviews
  - geoviews
  - datashader
  - hvplot
  - panel
  - requests
  - pandas
  - nbgitpuller
  - msgpack-python=0.6.2
  - dask
  - pip
  - pip:
    - git+https://github.com/ajelenak/xarray.git@zarr-chunkstore
    - git+https://github.com/HDFGroup/zarr-python.git@hdf5
